database:
  host: localhost
  port: 5432
  user: postgres
  password: your_password
  dbname: test
  max_open_conns: 25
  max_idle_conns: 25
  time_zone: "Asia/Shanghai"
  log_level: 3
redis:
  host: localhost
  port: 6379
  password: your_password
  db: 0
  protocol: 2
  unstable_resp3: true
  max_size: 10000
  default_ttl: 5
local_cache:
  num_counters: 100000
  max_cost: 10000
  buffer_items: 64
  default_ttl: 15
